### ISSUE TITLE
ci cdツールをgithub actionsに移行する

### ISSUE THREAD

**Issue by Higakinn** [hgaiji/EDAR#20]
## travis ci →github actionsに移行
travis ciもpublic repoなら無料だと思っていたが、制限ができたらしい。。

そのため、public repoだと無料のgithub actionsに移行したい。

### 実行タイミング
- lint実行(CI)
- テスト実行(CI)
- docker image build ＆ docker image push(CI)
   - コンテナ管理はGitHub Container Registryで行う
     - https://www.kaizenprogrammer.com/entry/2020/09/03/060236   
- hostingサービスへのデプロイ(CD)
  - staging環境(firebase)
  - 本番環境(firebase)

**Comment by Higakinn** [comment]
https://github.co.jp/features/actions

**Comment by SHID4** [comment]
public だと ci は無料で出来るンゴねぇ

**Comment by hgaiji** [comment]
> public だと ci は無料で出来るンゴねぇ
cd もできるんじゃないかな？

travis ciも昔はpublicは無料だっだんだけどね。。
githubactionに移行するために検証中。。。。

**Comment by Higakinn** [comment]
ci cd実行後にslackに通知できるようにしたい。
- https://qiita.com/progrhyme/items/badf31978612b22dbf47
