### ISSUE TITLE
githubにPR/issueテンプレートを追加する

### ISSUE THREAD

**Issue by Higakinn** [hgaiji/EDAR#30]
# 実現したいこと
- githubのリポジトリにPR/issueテンプレートを用意することで、用意したテンプレートを使用できるようにする

# テンプレート例
## PR テンプレート
```
<!-- あくまでテンプレートなので必ずしもすべての項目を埋めなくてよい -->

# 概要
<!-- 変更の目的 もしくは 関連する Issue 番号 -->

# 変更内容
<!-- ビューの変更がある場合はスクショによる比較などがあるとわかりやすい -->

# 影響範囲
<!-- この関数を変更したのでこの機能にも影響がある、など -->

# 動作要件
<!-- 動作に必要な 環境変数 / 依存関係 / DBの更新 など -->

# 補足
<!-- レビューをする際に見てほしい点、ローカル環境で試す際の注意点、など -->
```
## ~~issueテンプレート(古いバージョンの指定方法)~~
```
<!-- あくまでテンプレートなので必ずしもすべての項目を埋めなくてよい -->

<!-- 要望のテンプレート -->
# 概要
# 目的
# 提案内容
# タスク
- [ ] 細かいタスクに分解できているなら書き出す

<!-- 不具合のテンプレート -->
# 概要
# 再現手順
# 修正しないとどう困るか
# 原因
# 修正案
```

参考
- 
- https://docs.github.com/ja/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

**Comment by Higakinn** [comment]
- `.github/CONTRIBUTING.md`
- `.github/PULL_REQUEST_TEMPLATE.md`
- `.github/ISSUE_TEMPLATE.md`

**Comment by Higakinn** [comment]
https://dev.classmethod.jp/articles/pull-request-template/

**Comment by Higakinn** [comment]
CONTRIBUTING.md について
- https://qiita.com/nyamogera/items/3fe6985b45fbd5377184#pull_request_templatecontributing%E3%82%92%E4%BD%9C%E3%82%8B

**Comment by Higakinn** [comment]
https://qiita.com/suzuki-hoge/items/04de7d779bed6572bb99

**Comment by hgaiji** [comment]
.

**Comment by Higakinn** [comment]
## issueテンプレート修正版
`.github/ISSUE_TEMPLATE/feature_request.md`

( `---`  の部分を含めてください。)
```
---
name: feature
about: 機能追加の場合はこちらを使用する
---
<!-- 要望のテンプレート -->
# 概要
# 目的
# 提案内容
# タスク
- [ ] 細かいタスクに分解できているなら書き出す

```

`.github/ISSUE_TEMPLATE/bug_report.md`

```
---
name: bug
about: バグの場合はこちらを使用する
---
<!-- 不具合のテンプレート -->
# 概要
# 再現手順
# 修正しないとどう困るか
# 原因
# 修正案
```

**Comment by hgaiji** [comment]
`.github/ISSUE_TEMPLATE/bug_report.md`

```
---
name: bug
about: バグの場合はこちらを使用する

---
<!-- 不具合のテンプレート -->
# 概要
# 再現手順
# 修正しないとどう困るか
# 原因
# 修正案
```

**Comment by Higakinn** [comment]
https://docs.github.com/ja/github/building-a-strong-community/manually-creating-a-single-issue-template-for-your-repository
