### ISSUE TITLE
ワイヤーフレームを用いてどのような webページとするかを仮ぎめする

### ISSUE THREAD

**Issue by Higakinn** [hgaiji/EDAR#4]
## やること
今回作成するアプリケーションのwebページの設計図をワイヤーフレームを用いて作成する

### 参考
https://nandemo-nobiru.com/web-5695#0100
https://liginc.co.jp/web/tool/157624

**Comment by Yuki-TU** [comment]
大枠は以下の通り。
今後は、ロゴも作成も検討する。
おすすめ表示に何を表示するのか、どのように表示するのか、
また、トップページのサイトイメージはどうするのか、キャッチコピーなどを考える必要あり。
![image](https://user-images.githubusercontent.com/51454617/104846832-e376bd00-591f-11eb-90f2-a06d02524625.png)
![image](https://user-images.githubusercontent.com/51454617/104846870-13be5b80-5920-11eb-9e7d-6a62b84629f1.png)

**Comment by Higakinn** [comment]
> 大枠は以下の通り。
> 今後は、ロゴも作成も検討する。
> おすすめ表示に何を表示するのか、どのように表示するのか、
> また、トップページのサイトイメージはどうするのか、キャッチコピーなどを考える必要あり。
> ![image](https://user-images.githubusercontent.com/51454617/104846832-e376bd00-591f-11eb-90f2-a06d02524625.png)
> ![image](https://user-images.githubusercontent.com/51454617/104846870-13be5b80-5920-11eb-9e7d-6a62b84629f1.png)

ひとまず、このデザインで開発をすすめる。

**Comment by Higakinn** [comment]
おすすめ部分は、店名だけでなく、店の画像などもほしい。
https://material-ui.com/components/cards/#complex-interaction****

**Comment by Higakinn** [comment]
https://drive.google.com/drive/u/0/folders/1FhyaI-ozvHLsYEuzip9tmwJMZX8Ssnva

**Comment by SHID4** [comment]
ドラクエにしか見えん
![image](https://user-images.githubusercontent.com/19730407/106311785-03f03100-62a9-11eb-8c94-054c5a96dbb2.png)

**Comment by SHID4** [comment]
ドラクエにしか見えん
https://github.com/hgaiji/EDAR/issues/4
